name: Emergency Update

on:
  workflow_dispatch: # للتشغيل اليدوي فقط الآن حتى نصلح الخطأ

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install requests

      - name: Run Robot
        run: python update_matches.py

      - name: Push Changes
        run: |
          git config --global user.name "AtheerBot"
          git config --global user.email "bot@atheer.com"
          git add matches.json
          git commit -m "Update matches" || exit 0
          git push
